name: withergames
version: '7.0'
main: dev.withergames.withergames
api-version: '1.21'
depend: [Vault]
commands:
  tip:
    description: Tips your arrows (if you are at 75% worthiness)
  hearts:
    usage: /hearts [add|remove|reset] <amount> [player]
    description: Adds or removes hearts from a player
    permission: withergames.command.hearts
  test:
    usage: /test
    permission: withergames.command.test
  reset:
    usage: /reset [amulet|faction_weapon]
    permission: withergames.command.reset
  pedestal:
    description: Manage pedestals
    usage: /pedestal <place|refill|remove> [item_type]